const fs = require("fs");
const ts = new Date().toLocaleString();
fs.writeFileSync(
  "src/taskpane/buildInfo.ts",
  `// Auto-generated by prebuild.js — do not edit\nexport const BUILD_TIME = "${ts}";\n`
);
console.log(`[prebuild] Build timestamp: ${ts}`);
